# Generated by Django 5.1.1 on 2024-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tododetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=300)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
